CFLAGS = -std=c11 -Wall -Wextra

all: sudoku

sudoku:
	@cd src && $(MAKE)
	@cp -f src/$@ ./	
clean:
	@cd src && $(MAKE) clean
	rm -f *.o sudoku
help:
	@echo "Usage:"
	@echo " make [all]\t\tBuid the software"
	@echo " make clean\t\tRemove all files generated by make"
	@echo " make help\t\tDisplay this help"

.PHONY: all sudoku clean help
